MALACHOWSKY_CISE_DIRECTORY = [
    {
        "id": "mal-cise-anthony-lisa",
        "name": "Anthony, Lisa",
        "title": "Associate Professor, Director of Intelligent Natural Interaction Technology (INIT)",
        "affiliations": "AI Experts, Department of Computer and Information Science and Engineering, Faculty",
        "phone": "352-505-1589",
        "location": "MALA 5404",
        "email": "lanthony@cise.ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/lisaanthony/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/lisa-anthony/LisaAnthony-dir-5e4589d64b5badcb16de53fa30664ac3.jpg",
    },
    {
        "id": "mal-cise-boyer-kristy",
        "name": "Boyer, Kristy",
        "title": "Professor",
        "affiliations": "Faculty, Human-Centered Computing",
        "phone": "352-575-8974",
        "location": "MALA 5121",
        "email": "keboyer@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/kristy-boyer-6439072a/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/kristy-boyer/kristy-boyer-8796c5ddb856a4c2ed1c1bee66daf098.jpg",
    },
    {
        "id": "mal-cise-jain-eakta",
        "name": "Jain, Eakta",
        "title": "Associate Professor",
        "affiliations": "Algorithms, Faculty, Graphics and Visualization, Human-Centered Computing",
        "phone": "352-294-6653",
        "location": "MALA 5125",
        "email": "ejain@cise.ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/eakta-jain-6585484/",
        "image_url": "https://media-speakerfile-pre.s3.amazonaws.com/images_avatars/b8165092275c7133098fef87298819bb1687894195_l.jpg",
    },
    {
        "id": "mal-cise-peters-jorg",
        "name": "Peters, Jorg",
        "title": "Professor",
        "affiliations": "AI/Machine Learning, Computational Geometry, Faculty, Graphics and Visualization, Human-Centered Computing",
        "phone": "352-294-6661",
        "location": "MALA 3103",
        "email": "jorg@cise.ufl.edu",
        "linkedin_url": "",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/jorg-peters/Jorg-Peters-048fb89ac90b6e7a2b6ba88b96ce551f.jpg",
    },
    {
        "id": "mal-cise-ranka-sanjay",
        "name": "Ranka, Sanjay",
        "title": "Distinguished Professor",
        "affiliations": "Cloud Computing, Concurrency, Parallelism and High-Performance Computing, Database, Data Science and Informatics, Embedded Systems, Energy-Aware Computing, Faculty, Image & Signal Analysis",
        "phone": "352-514-4213",
        "location": "MALA 6112",
        "email": "ranka@cise.ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/sanjayranka/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/sanjay-ranka/Ranka_Sanjay-dir-688c5e5178c803f528c0e663e597b47a.jpg",
    },
    {
        "id": "mal-cise-sitharam-meera",
        "name": "Sitharam, Meera",
        "title": "Professor",
        "affiliations": "AI/Machine Learning, Algorithms, Bioinformatics, Computational Geometry, Faculty",
        "phone": "352-294-6670",
        "location": "MALA 3107",
        "email": "sitharam@cise.ufl.edu",
        "linkedin_url": "",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/meera-sitharam/Sitharam-Meera-86877d5ab37b836c4008fede262f6ace.jpg",
    },
    {
        "id": "mal-cise-vemuri-baba-c",
        "name": "Vemuri, Baba C.",
        "title": "Distinguished Professor",
        "affiliations": "Computer Vision & Medical Image Computing, Faculty, Image & Signal Analysis",
        "phone": "352-682-6482",
        "location": "MALA 3118",
        "email": "vemuri@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/baba-vemuri-22955545/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/baba-vemuri/vemuri-baba-29efadd7472695fccd6f3e70a6a03b32.jpg",
    },
    {
        "id": "mal-cise-wang-daisy-zhe",
        "name": "Wang, Daisy Zhe",
        "title": "Professor",
        "affiliations": "Database, Data Science and Informatics, Faculty",
        "phone": "352-294-6677",
        "location": "MALA 6109",
        "email": "daisyw@cise.ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/daisy-zhe-wang-8ab9813/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/daisy-wang/2025_CISE_Daisy-Zhe-Wang_2-1618f8949d3e29f69f95ace6439cd9d3.jpg",
    },
    {
        "id": "mal-cise-mcmullen-kyla",
        "name": "McMullen, Kyla",
        "title": "Associate Professor",
        "affiliations": "Faculty, Human-Centered Computing",
        "phone": "352-392-1200",
        "location": "MALA 5122",
        "email": "drkyla@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/kyla-mcmullen-ph-d-16902222/",
        "image_url": "https://cise.ufl.edu/wp-content/uploads/sites/15/connections-images/kyla-mcmullen/2025_CISE_Kyla-McMullen_3-c33ee5bb6fcdf82ff3c90489ba847dc5.jpg",
    },
]
