def _opp(
    *,
    title: str,
    description: str,
    summary: str,
    department: str,
    professor: str,
    tags: list[str],
    contact: str,
    deadline: str,
    hourly_commitment: str,
    pay: str,
    terms_available: str,
    student_level: str,
    prerequisites: str,
    credit: str,
    stipend: str,
    application_requirements: str,
    url: str = "",
    phd_student_mentors: str = "TBD",
    professor_id: str = "",
) -> dict:
    data = {
        "type": "research",
        "title": title,
        "description": description,
        "summary": summary,
        "department": department,
        "professor": professor,
        "phd_student_mentors": phd_student_mentors,
        "terms_available": terms_available,
        "student_level": student_level,
        "prerequisites": prerequisites,
        "credit": credit,
        "stipend": stipend,
        "application_requirements": application_requirements,
        "tags": tags,
        "contact": contact,
        "deadline": deadline,
        "hourly_commitment": hourly_commitment,
        "pay": pay,
        "goal_tags": ["research", "career"],
    }
    if professor_id:
        data["professor_id"] = professor_id
    if url:
        data["url"] = url
    return data


MALACHOWSKY_RESEARCH_OPPORTUNITIES = [
    _opp(
        title="Intelligent Natural Interaction Technology (INIT) Lab",
        description="Advanced interaction technologies such as touch, gesture, voice, and mixed reality in human-AI interaction, education, healthcare, and serious games.",
        summary="Natural interaction, human-AI interaction, health, education, and serious games research.",
        department="Computer and Information Sciences and Engineering",
        professor="Anthony, Lisa",
        professor_id="mal-cise-anthony-lisa",
        phd_student_mentors="TBD based on project and availability",
        terms_available="Fall, Spring, Summer",
        student_level="Freshman, Sophomore, Junior, Senior; 2-3 students per semester",
        prerequisites="Programming fundamentals, experimental design, data analysis, experience working with children, people skills, attention to detail, organization, and time management are helpful but not required.",
        credit="0-3 credits via EGN 4912",
        stipend="1st semester none unless selected for University Scholars; after trial period, $15/hour up to 10 hours per week",
        application_requirements="Resume, UF unofficial transcripts, faculty interview; email all application requirements to Lisa Anthony at lanthony@cise.ufl.edu to request an interview.",
        tags=["HCI", "AI", "Mixed Reality", "Education", "Healthcare"],
        contact="lanthony@cise.ufl.edu",
        url="http://init.cise.ufl.edu",
        deadline="Rolling basis; recommended Mar 15 or Jul 1 for Fall, Nov 15 for Spring, Mar 15 for Summer",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$15/hr after trial period",
    ),
    _opp(
        title="Modeling Dialogue for Supporting Learning",
        description="Understanding and modeling dialogue for learning to better support students through intelligent learning environments.",
        summary="Computational dialogue models for learning environments.",
        department="Computer and Information Sciences and Engineering",
        professor="Boyer, Kristy",
        professor_id="mal-cise-boyer-kristy",
        phd_student_mentors="Mentor will be selected to best fit the undergraduate applicant.",
        terms_available="Fall, Spring, Summer",
        student_level="Freshman, Sophomore, Junior, Senior; 2 students per semester",
        prerequisites="Projects can be customized according to student background. Java I and Java II strongly preferred; Data Structures opens the most possibilities.",
        credit="0-3 credits via EGN 4912",
        stipend="$10/hour; hours per week flexible",
        application_requirements="Resume, UF unofficial transcripts, faculty interview; email resume, transcript, and cover letter to Timothy Brown at timothy.brown@ufl.edu.",
        tags=["Dialogue", "Learning", "AI", "Education"],
        contact="keboyer@ufl.edu",
        url="https://www.cise.ufl.edu/research/learndialogue/",
        deadline="Rolling",
        hourly_commitment="Flexible",
        pay="$10/hr",
    ),
    _opp(
        title="Validating Wearable Technology and Machine Learning for Exposure Assessment on Uneven Surfaces",
        description="Use wearable sensors and deep learning to study gait behavior and detect walking surface categories during typical workplace tasks.",
        summary="Wearables, gait signals, and deep learning for workplace exposure assessment.",
        department="Computer and Information Science and Engineering, Industrial and Systems Engineering, and Electrical and Computer Engineering",
        professor="Hu, Boyi",
        phd_student_mentors="TBD based on project and availability",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; 1-2 students per semester",
        prerequisites="At least 1 year of programming experience (Matlab or Python preferred), signal processing fundamentals, and machine learning fundamentals.",
        credit="0-3 credits via EGN 4912",
        stipend="$12/hour up to 20 hours per week",
        application_requirements="Resume, UF unofficial transcripts, statement of research interest, faculty interview; email one PDF of all requirements to Boyi Hu at boyihu@ise.ufl.edu.",
        tags=["Wearables", "Machine Learning", "Signal Processing", "Workplace Safety"],
        contact="boyihu@ise.ufl.edu",
        deadline="N/A",
        hourly_commitment="Up to 20 hrs/week",
        pay="$12/hr",
    ),
    _opp(
        title="Collecting Eyetracking Data on Images and Videos",
        description="Design, code, and run experimental studies to collect and analyze eyetracking data and understand visual perception.",
        summary="Eyetracking studies focused on human visual perception.",
        department="Computer and Information Science and Engineering",
        professor="Jain, Eakta",
        professor_id="mal-cise-jain-eakta",
        phd_student_mentors="n/a",
        terms_available="Fall, Spring",
        student_level="Junior, Senior; 2 students a term",
        prerequisites="Programming fundamentals, strong organization and time management, and ability to code in MATLAB.",
        credit="0-3 credits via EGN 4912",
        stipend="None in the first semester unless selected for University Scholar; hourly stipend may be available later.",
        application_requirements="Resume, faculty interview, attend a group meeting; email ejain@cise.ufl.edu with PDF resume to schedule an interview.",
        tags=["Eyetracking", "MATLAB", "Perception", "Experiment Design"],
        contact="ejain@cise.ufl.edu",
        url="http://jainlab.cise.ufl.edu",
        deadline="End of add/drop period in each term",
        hourly_commitment="TBD",
        pay="TBD after first semester",
    ),
    _opp(
        title="Web Development and Server Management",
        description="Maintain databases and citizen science project pages on the Jain Lab web server.",
        summary="Web development and server management for research lab infrastructure.",
        department="Computer and Information Science and Engineering",
        professor="Jain, Eakta",
        professor_id="mal-cise-jain-eakta",
        phd_student_mentors="n/a",
        terms_available="Fall, Spring",
        student_level="Sophomore, Junior; 1 student a term",
        prerequisites="HTML programming plus good time management, organization, and previous web development experience.",
        credit="0-3 credits via EGN 4912",
        stipend="None in the first semester unless selected for University Scholar; hourly stipend may be available later.",
        application_requirements="Resume, faculty interview, attend a group meeting; email PDF resume to ejain@cise.ufl.edu.",
        tags=["Web Development", "Servers", "Databases", "Research Infrastructure"],
        contact="ejain@cise.ufl.edu",
        url="http://jainlab.cise.ufl.edu",
        deadline="End of add/drop period in each term",
        hourly_commitment="TBD",
        pay="TBD after first semester",
    ),
    _opp(
        title="Modeling Geometry in Virtual Reality",
        description="Move modeling tasks into a head-mounted display environment using VR-focused workflows.",
        summary="Virtual reality geometry and modeling research.",
        department="Computer and Information Science and Engineering",
        professor="Peters, Jorg",
        professor_id="mal-cise-peters-jorg",
        phd_student_mentors="n/a",
        terms_available="Fall, Summer",
        student_level="Junior or Senior; 2 students a term",
        prerequisites="Experience with Unity, Blender, or similar modeling environments; graphics programming experience; enthusiasm for VR.",
        credit="0-3 credits via EGN 4912",
        stipend="TBD",
        application_requirements="UF unofficial transcripts, faculty interview, and short explanation of interest/qualifications; email jorg@cise.com.",
        tags=["VR", "Geometry", "Graphics", "Unity"],
        contact="jorg@cise.com",
        url="http://www.cise.ufl.edu/research/SurfLab/",
        deadline="Rolling",
        hourly_commitment="TBD",
        pay="TBD",
    ),
    _opp(
        title="Big Data Technologies for Actigraphy Problems",
        description="Develop techniques for collecting, monitoring, and modeling activity information of older adults and correlating it with physical and mental health.",
        summary="Big data methods for actigraphy and older-adult health modeling.",
        department="Computer and Information Sciences and Engineering",
        professor="Ranka, Sanjay",
        professor_id="mal-cise-ranka-sanjay",
        phd_student_mentors="n/a",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; 2 students per term",
        prerequisites="Strong programming and algorithmic background.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars",
        application_requirements="Resume and UF unofficial transcripts; email one PDF file of all documents to ranka@cise.ufl.edu.",
        tags=["Big Data", "Health", "Actigraphy", "Algorithms"],
        contact="ranka@cise.ufl.edu",
        url="http://www.cise.ufl.edu/~ranka",
        deadline="March 1 for Summer and Fall; November 1 for Spring",
        hourly_commitment="TBD",
        pay="University Scholars only",
    ),
    _opp(
        title="Big Data and Machine Learning",
        description="Apply big-data and machine learning techniques to transportation, health care, and smart city domains.",
        summary="Big data and machine learning across applied domains.",
        department="Computer and Information Sciences and Engineering",
        professor="Ranka, Sanjay",
        professor_id="mal-cise-ranka-sanjay",
        phd_student_mentors="n/a",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; 5 students per term",
        prerequisites="Expertise in data structures and programming. A course in machine learning is a plus.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars",
        application_requirements="Resume and UF unofficial transcripts; email one PDF file of all documents to ranka@cise.ufl.edu.",
        tags=["Big Data", "Machine Learning", "Transportation", "Healthcare", "Smart Cities"],
        contact="ranka@cise.ufl.edu",
        url="http://www.cise.ufl.edu/~ranka",
        deadline="Open",
        hourly_commitment="TBD",
        pay="University Scholars only",
    ),
    _opp(
        title="In House Open Source Molecular and Materials Modeling Software",
        description="Understand new theory and algorithms, implement them in software, and incorporate them into a C++ and QT/webGL modeling suite.",
        summary="Software engineering and modeling tools for molecular and materials research.",
        department="Computer and Information Sciences and Engineering",
        professor="Sitharam, Meera",
        professor_id="mal-cise-sitharam-meera",
        phd_student_mentors="Rahul Prabhu, rprabhu@ufl.edu",
        terms_available="Fall, Spring, Summer; ideally for an entire year",
        student_level="Freshman, Sophomore, Junior, Senior; 1 student per semester, ideally at least a year",
        prerequisites="Should be able to read and write C++, QT OpenGL/webGL or similar object-oriented graphics languages, and work with MATLAB.",
        credit="0-3 credits via EGN 4912",
        stipend="$15/hour up to 10 hrs/week",
        application_requirements="Basic online application and faculty interview; email one PDF file with qualifications to rprabhu@ufl.edu.",
        tags=["C++", "OpenGL", "WebGL", "Modeling Software", "MATLAB"],
        contact="rprabhu@ufl.edu",
        url="http://www.cise.ufl.edu/~sitharam/EASALvideo.mpg",
        deadline="Rolling until hired",
        hourly_commitment="Up to 10 hrs/week",
        pay="$15/hr",
    ),
    _opp(
        title="Development of Autonomous Mobile Agents (Robots)",
        description="MIL studies and develops intelligent autonomous robots spanning machine learning, sensor integration, optimization, and control.",
        summary="Autonomous robotics research in the Machine Intelligence Laboratory.",
        department="Electrical and Computer Engineering, Computer and Information Science and Engineering, Mechanical and Aerospace Engineering",
        professor="Schwartz, Eric",
        phd_student_mentors="N/A",
        terms_available="Fall, Spring, Summer",
        student_level="Freshman, Sophomore, Junior, Senior; 15-50 students per term",
        prerequisites="A desire to learn and work with others.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars or Emerging Scholars",
        application_requirements="Faculty interview; email ems@ufl.edu to set up an appointment.",
        tags=["Robotics", "Autonomy", "Sensors", "Control", "Machine Learning"],
        contact="ems@ufl.edu",
        url="http://www.mil.ufl.edu",
        deadline="ASAP",
        hourly_commitment="TBD",
        pay="None unless funded",
    ),
    _opp(
        title="Geometry Aware Machine Learning for Computer Vision and Medical Imaging",
        description="Develop computationally efficient algorithms that exploit the intrinsic geometry of high-dimensional, non-Euclidean data spaces.",
        summary="Geometry-aware machine learning for vision and imaging data.",
        department="Computer and Information Sciences and Engineering",
        professor="Vemuri, Baba C.",
        professor_id="mal-cise-vemuri-baba-c",
        phd_student_mentors="NA",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; variable number of students per semester",
        prerequisites="Linear Algebra, Vector Calculus, Numerical Analysis, Probability and Statistics, and proficiency in Python, MATLAB, or C++.",
        credit="0-3 credits via EGN 4912",
        stipend="None initially; may depend on performance and funding availability.",
        application_requirements="Resume, UF unofficial transcripts, faculty interview; email one PDF file to vemuri@cise.ufl.edu.",
        tags=["Machine Learning", "Geometry", "Computer Vision", "Medical Imaging"],
        contact="vemuri@cise.ufl.edu",
        url="http://www.cise.ufl.edu/~vemuri",
        deadline="N/A",
        hourly_commitment="TBD",
        pay="None initially",
    ),
    _opp(
        title="Demo UI Development for Advanced QA over Knowledge Bases",
        description="Develop front-end demos for advanced question-answering scenarios over knowledge bases.",
        summary="UI development for advanced QA systems over knowledge bases.",
        department="Computer and Information Science and Engineering",
        professor="Wang, Daisy Zhe",
        professor_id="mal-cise-wang-daisy-zhe",
        phd_student_mentors="Xiaofeng Zhou, xiaofengzhou@ufl.edu; Miguel Rodriguez, miguelrodriguez@ufl.edu",
        terms_available="Fall",
        student_level="Junior, Senior; 1-2 students a term",
        prerequisites="Past experience with UI design and development; Data Structures and Programming.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars; after a trial period, $10/hour up to 10 hours a week",
        application_requirements="Resume, UF unofficial transcripts, good GPA; email one PDF file of requirements to daisyw@cise.ufl.edu.",
        tags=["UI Development", "Knowledge Bases", "QA", "Front End"],
        contact="daisyw@cise.ufl.edu",
        url="http://dsr.cise.ufl.edu/projects/",
        deadline="Rolling deadline effective until September 2016",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$10/hr after trial period",
    ),
    _opp(
        title="Data Science Application to Law, Ecology and Biomedical Domains",
        description="Apply state-of-the-art data science methods to law, ecology, and biomedical research in collaboration with domain experts.",
        summary="Cross-domain applied data science research.",
        department="Computer and Information Science and Engineering",
        professor="Wang, Daisy Zhe",
        professor_id="mal-cise-wang-daisy-zhe",
        phd_student_mentors="n/a",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; 1-2 students a term",
        prerequisites="Interest and prior knowledge in law, ecology, or biomedical domains, plus data structures, programming, databases, and machine learning.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars; after a trial period, $10/hour up to 10 hours a week",
        application_requirements="Resume, UF unofficial transcripts, faculty interview, and good GPA; email one PDF file of requirements to daisyw@cise.ufl.edu.",
        tags=["Data Science", "Law", "Ecology", "Biomedical", "Machine Learning"],
        contact="daisyw@cise.ufl.edu",
        url="http://dsr.cise.ufl.edu/projects/",
        deadline="Rolling deadline effective until September 2016",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$10/hr after trial period",
    ),
    _opp(
        title="Biomedical Applications of Magnetic Nanoparticles",
        description="Interdisciplinary biomedical nanoparticle research spanning imaging, therapeutic delivery, nanoscale thermal therapy, and computational analysis.",
        summary="Interdisciplinary nanoparticle research spanning biomedical imaging and therapy.",
        department="Biomedical Engineering, Chemical Engineering, Electrical Engineering, Computer Science and Engineering, Materials Science and Engineering, Mechanical Engineering",
        professor="Rinaldi-Ramos, Carlos",
        phd_student_mentors="varies",
        terms_available="Fall, Spring, Summer",
        student_level="Sophomore, Junior; 2-5 students per term",
        prerequisites="Passion for science and engineering, interest in research, and self-driven work habits.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars",
        application_requirements="Resume and statement of research interest; email one PDF file with all application requirements to carlos.rinaldi@ufl.edu.",
        tags=["Nanoparticles", "Biomedical Imaging", "Therapy", "Interdisciplinary Research"],
        contact="carlos.rinaldi@ufl.edu",
        url="http://www.bme.ufl.edu/labs/rinaldi/",
        deadline="March 1 for Summer and Fall; November 1 for Spring",
        hourly_commitment="TBD",
        pay="University Scholars only",
    ),
    _opp(
        title="Numerical Computing and Visualization",
        description="Work on geometry, graphics, and computational projects with an emphasis on math, computing, and visualization tools.",
        summary="Geometry, graphics, and numerical computing projects.",
        department="Computer and Information Science and Engineering",
        professor="Peters, Jorg",
        professor_id="mal-cise-peters-jorg",
        phd_student_mentors="varies",
        terms_available="Fall, Spring, Summer",
        student_level="Sophomore, Junior, Senior; 2 students per term",
        prerequisites="Discrete Math and Matlab; you will learn various geometry and graphics tools.",
        credit="0-3 credits via EGN 4912",
        stipend="None unless selected for University Scholars",
        application_requirements="Official University transcript required. Email Professor Peters if interested.",
        tags=["Numerical Computing", "Visualization", "Geometry", "Graphics", "Matlab"],
        contact="jorg@cise.ufl.edu",
        url="https://www.cise.ufl.edu/research/SurfLab/",
        deadline="Open until filled",
        hourly_commitment="TBD",
        pay="University Scholars only",
    ),
    _opp(
        title="Project #1 – Spatial Audio Localization Research",
        description="Help collect personalized HRTF data, process 3-D head meshes, perform perception tests, and analyze data related to spatial audio localization.",
        summary="Spatial audio localization and personalized HRTF research.",
        department="Computer and Information Science and Engineering",
        professor="McMullen, Kyla",
        professor_id="mal-cise-mcmullen-kyla",
        phd_student_mentors="Chenshen (Jason) Wan",
        terms_available="Summer",
        student_level="Freshman, Sophomore, Junior, Senior; 1 student per semester",
        prerequisites="Java Programming, Data Structures, and signal processing would be helpful.",
        credit="3 credits via EGN 4912",
        stipend="None unless selected for University Scholars; after a trial period, $10/hour up to 10 hours a week",
        application_requirements="Resume and faculty interview; email drkyla@ufl.edu with your resume to request an interview.",
        tags=["Spatial Audio", "HRTF", "Signal Processing", "Perception", "Java"],
        contact="drkyla@ufl.edu",
        url="https://faculty.eng.ufl.edu/soundpad-lab/",
        deadline="Open until filled",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$10/hr after trial period",
    ),
    _opp(
        title="Project #2 – Altering Sonic Cues to Improve Real-World Target Detection with 3D Audio",
        description="Work on human-centered studies and MATLAB analysis exploring how 3D audio can improve target localization in low-visibility scenarios.",
        summary="3D audio research for real-world target detection.",
        department="Computer and Information Science and Engineering",
        professor="McMullen, Kyla",
        professor_id="mal-cise-mcmullen-kyla",
        phd_student_mentors="Armisha Roberts",
        terms_available="Fall, Spring, Summer",
        student_level="Junior, Senior; 1 student per semester",
        prerequisites="Java Programming and Data Structures.",
        credit="3 credits via EGN 4912",
        stipend="None unless selected for University Scholars; after a trial period, $10/hour up to 10 hours a week",
        application_requirements="Resume and faculty interview; email drkyla@ufl.edu with your resume to request an interview.",
        tags=["3D Audio", "Human-Centered Studies", "MATLAB", "First Responders"],
        contact="drkyla@ufl.edu",
        url="https://faculty.eng.ufl.edu/soundpad-lab/",
        deadline="Open until filled",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$10/hr after trial period",
    ),
    _opp(
        title="Project #3 – An Augmented Reality Corsi Block-Tapping Test Framework",
        description="Assist with subject studies, data collection, analysis, and possibly Unity development for AR/VR spatial memory testing frameworks.",
        summary="AR spatial memory framework research using the Corsi Block-Tapping Test.",
        department="Computer and Information Science and Engineering",
        professor="McMullen, Kyla",
        professor_id="mal-cise-mcmullen-kyla",
        phd_student_mentors="Terek Arce",
        terms_available="Fall, Spring, Summer",
        student_level="Sophomore, Junior, Senior; 1 student per semester",
        prerequisites="Programming 1 and Data Structures. Familiarity with C#, Matlab, Python, and Unity is helpful but not required.",
        credit="3 credits via EGN 4912",
        stipend="None unless selected for University Scholars; after a trial period, $10/hour up to 10 hours a week",
        application_requirements="Resume and faculty interview; email drkyla@ufl.edu with your resume to request an interview.",
        tags=["Augmented Reality", "Unity", "Spatial Memory", "User Studies", "VR"],
        contact="drkyla@ufl.edu",
        url="https://faculty.eng.ufl.edu/soundpad-lab/",
        deadline="Open until filled",
        hourly_commitment="Up to 10 hrs/week after trial period",
        pay="$10/hr after trial period",
    ),
]
