MALACHOWSKY_EVENTS = [
    {
        "type": "event",
        "title": "Fishbowl Fridays",
        "summary": "Weekly ACM social for casual conversations, networking, games, and community building.",
        "description": "A weekly social hosted by ACM where students gather for casual conversations, networking, games, and community building. Open to all majors, Fishbowl Fridays provide a relaxed environment to meet peers in computing and unwind after classes.",
        "hosted_by": "Association for Computing Machinery (ACM) at UF",
        "location_detail": "Malachowsky Hall - Fishbowl Collaboration Space (1st Floor)",
        "tags": ["ACM", "Social", "Networking", "Community"],
        "contact": "Association for Computing Machinery (ACM) at UF",
        "deadline": "Every Friday during the semester",
        "hourly_commitment": "1:00 PM - 3:00 PM",
        "pay": "Free",
        "goal_tags": ["social_support", "career"],
    },
    {
        "type": "event",
        "title": "AI Research Lightning Talks: Spring Showcase",
        "summary": "Short research talks plus Q&A and networking with labs seeking undergraduate assistants.",
        "description": "Graduate students and faculty present short 5-minute lightning talks highlighting ongoing artificial intelligence and data science research projects. Includes Q&A and networking with research labs seeking undergraduate assistants.",
        "hosted_by": "UF CISE Department",
        "location_detail": "NVIDIA Auditorium, Malachowsky Hall",
        "tags": ["AI", "Research", "Networking", "Lightning Talks"],
        "contact": "UF CISE Department",
        "deadline": "March 11, 2026",
        "hourly_commitment": "4:00 PM - 6:00 PM",
        "pay": "Free",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "event",
        "title": "Engineering Career Pop-Up - Resume & LinkedIn Reviews",
        "summary": "Drop-in advising for resumes, portfolios, and LinkedIn profiles with tech-focused career coaches.",
        "description": "Drop-in advising session where students receive personalized feedback on resumes, portfolios, and LinkedIn profiles from career coaches specializing in technology roles.",
        "hosted_by": "UF Career Connections Center",
        "location_detail": "Room 2301, Malachowsky Hall",
        "tags": ["Career", "Resume", "LinkedIn", "Advising"],
        "contact": "UF Career Connections Center",
        "deadline": "March 18, 2026",
        "hourly_commitment": "11:00 AM - 1:00 PM",
        "pay": "Free",
        "goal_tags": ["career"],
    },
    {
        "type": "event",
        "title": "Biomedical AI Seminar: Machine Learning for Clinical Prediction",
        "summary": "Faculty seminar on machine learning in healthcare prediction systems and ethical AI.",
        "description": "Faculty seminar exploring how machine learning models are used in healthcare prediction systems. Includes discussion on ethical AI and interdisciplinary collaboration between engineering and medicine.",
        "hosted_by": "UF Biomedical AI Collaborative",
        "location_detail": "NVIDIA Auditorium, Malachowsky Hall",
        "tags": ["Biomedical AI", "Healthcare", "Seminar", "Machine Learning"],
        "contact": "UF Biomedical AI Collaborative",
        "deadline": "March 24, 2026",
        "hourly_commitment": "3:30 PM - 5:00 PM",
        "pay": "Free",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "event",
        "title": "Intro to Cybersecurity CTF Workshop",
        "summary": "Beginner-friendly cybersecurity capture-the-flag workshop covering core security challenge types.",
        "description": "Hands-on workshop introducing students to cybersecurity competitions through beginner-friendly capture-the-flag challenges covering cryptography, web security, and reverse engineering.",
        "hosted_by": "Florida Institute for Cybersecurity Research (FICS)",
        "location_detail": "Innovation Lab 3200, Malachowsky Hall",
        "tags": ["Cybersecurity", "CTF", "Workshop", "Hands-On"],
        "contact": "Florida Institute for Cybersecurity Research (FICS)",
        "deadline": "April 2, 2026",
        "hourly_commitment": "6:00 PM - 8:30 PM",
        "pay": "Free",
        "goal_tags": ["career", "research"],
    },
    {
        "type": "event",
        "title": "Careers in Semiconductors: Industry Panel",
        "summary": "Industry panel on semiconductor careers, internships, and chip-design trends.",
        "description": "Industry professionals discuss career paths in semiconductor engineering, internships, and emerging trends in chip design followed by student networking.",
        "hosted_by": "UF Semiconductor Career Readiness Organization (SCRO)",
        "location_detail": "Lecture Hall C1-015, Malachowsky Hall",
        "tags": ["Semiconductors", "Industry", "Panel", "Networking"],
        "contact": "UF Semiconductor Career Readiness Organization (SCRO)",
        "deadline": "April 8, 2026",
        "hourly_commitment": "5:30 PM - 7:30 PM",
        "pay": "Free",
        "goal_tags": ["career"],
    },
]
