MALACHOWSKY_OPPORTUNITIES = [
    {
        "type": "job",
        "title": "Undergraduate Research Assistant Opportunities",
        "summary": "Join active labs in AI, data science, semiconductors, robotics, and advanced computing.",
        "description": "Students can join active research labs in Malachowsky Hall focused on artificial intelligence, data science, semiconductor technology, robotics, and advanced computing. Opportunities include volunteer research, course credit, honors thesis work, or paid positions depending on lab funding.",
        "next_steps": "Visit Malachowsky Hall and identify active labs.\nAttend a research seminar or talk.\nEmail a professor or speak with graduate students about openings.\nApply for undergraduate research credit through your department.",
        "tags": ["Research", "Labs", "AI", "Robotics", "Semiconductors"],
        "contact": "CISE faculty and graduate research labs",
        "hourly_commitment": "Varies by lab",
        "pay": "Volunteer, credit, thesis, or paid depending on funding",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "course",
        "title": "Technical Seminar & Guest Speaker Series",
        "summary": "Recurring seminars featuring researchers, engineers, and visiting scholars.",
        "description": "Malachowsky Hall hosts recurring technical seminars featuring researchers, industry engineers, and visiting scholars. Students can learn about emerging technologies, research breakthroughs, and career paths while networking with professionals.",
        "next_steps": "Check building bulletin boards or department mailing lists.\nAttend open seminars.\nIntroduce yourself to speakers after sessions.\nConnect with presenters on LinkedIn.",
        "tags": ["Seminars", "Guest Speakers", "Networking", "Emerging Tech"],
        "contact": "UF CISE Department and partner institutes",
        "hourly_commitment": "Varies by event",
        "pay": "Free",
        "goal_tags": ["career", "research"],
    },
    {
        "type": "student_org",
        "title": "Makerspace & Project Development Access",
        "summary": "Use collaborative innovation spaces for robotics, IoT, software, and startup prototypes.",
        "description": "Collaborative innovation spaces allow students to build personal or academic projects such as robotics systems, IoT devices, software applications, and startup prototypes. These spaces support hands-on learning and portfolio development.",
        "next_steps": "Reserve collaborative workspace if required.\nForm a project team or join an existing one.\nUse the space for hackathon or class projects.\nDocument projects for resumes or portfolios.",
        "tags": ["Makerspace", "Projects", "IoT", "Robotics", "Startups"],
        "contact": "Malachowsky collaboration and innovation spaces",
        "hourly_commitment": "Flexible",
        "pay": "Free",
        "goal_tags": ["career", "academic_aid"],
    },
    {
        "type": "job",
        "title": "Industry Networking & Career Mixers",
        "summary": "Meet employers in semiconductors, AI, computing, and technology fields.",
        "description": "Industry partners regularly host networking events connecting students with employers in semiconductor engineering, AI, computing, and technology fields. Events often include career discussions and internship exploration.",
        "next_steps": "Watch UF engineering or institute event calendars.\nAttend networking mixers.\nPrepare a resume and elevator pitch.\nFollow up with recruiters after events.",
        "tags": ["Industry", "Networking", "Internships", "Careers"],
        "contact": "UF engineering and institute career programming",
        "hourly_commitment": "Varies by event",
        "pay": "Free",
        "goal_tags": ["career", "social_support"],
    },
    {
        "type": "course",
        "title": "HiPerGator Supercomputing Access",
        "summary": "Access UF high-performance computing resources for AI, data, and simulation work.",
        "description": "Students involved in certain courses or research projects can access UF's high-performance computing resources to run AI models, large datasets, and advanced simulations.",
        "next_steps": "Join a research group or qualifying course.\nRequest access through a faculty sponsor.\nComplete required training modules.\nUse computing resources for projects or research.",
        "tags": ["HiPerGator", "Supercomputing", "AI", "Data", "Simulation"],
        "contact": "Faculty sponsor and UF Research Computing",
        "hourly_commitment": "Project-based",
        "pay": "Resource access through approved coursework or research",
        "goal_tags": ["research", "academic_aid"],
    },
    {
        "type": "course",
        "title": "Student Research Conferences & Academic Events",
        "summary": "Attend, volunteer at, or present in research showcases and academic events.",
        "description": "Academic conferences and research showcases hosted in Malachowsky Hall allow students to attend talks, volunteer, or present research work alongside faculty and visiting scholars.",
        "next_steps": "Monitor UF event announcements.\nRegister or volunteer for conferences.\nAttend presentations relevant to your major.\nNetwork with researchers and attendees.",
        "tags": ["Conferences", "Research Showcase", "Academic Events", "Networking"],
        "contact": "UF event announcements and conference organizers",
        "hourly_commitment": "Varies by conference",
        "pay": "Free or volunteer-based",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "student_org",
        "title": "Collaborative Study & Innovation Spaces",
        "summary": "Use open collaboration areas to study, brainstorm, and meet peers across engineering and data science.",
        "description": "Open collaboration areas provide whiteboards, group seating, and shared environments where students can study, brainstorm projects, and connect with peers across engineering and data science disciplines.",
        "next_steps": "Use open study areas for group work.\nJoin discussions or student project teams.\nNetwork with students working nearby.\nOrganize study or coding sessions.",
        "tags": ["Study Spaces", "Innovation", "Collaboration", "Peer Networking"],
        "contact": "Malachowsky open collaboration areas",
        "hourly_commitment": "Flexible",
        "pay": "Free",
        "goal_tags": ["academic_aid", "social_support"],
    },
    {
        "type": "student_org",
        "title": "STEM Outreach & Volunteer Programs",
        "summary": "Participate in outreach, lab tours, and STEM education programming tied to Malachowsky research.",
        "description": "Students can participate in outreach events, lab tours, and STEM education programs connected to research activities at Malachowsky Hall, gaining leadership and service experience.",
        "next_steps": "Sign up for volunteer opportunities.\nAssist with lab demonstrations or tours.\nParticipate in outreach events.\nTrack hours for resumes or service credits.",
        "tags": ["STEM Outreach", "Volunteering", "Leadership", "Service"],
        "contact": "Malachowsky outreach and lab event coordinators",
        "hourly_commitment": "Flexible",
        "pay": "Volunteer/service experience",
        "goal_tags": ["social_support", "career"],
    },
]
