NEW_PHYSICS_EVENTS = [
    {
        "type": "event",
        "title": "High Energy Physics Seminar - Benoit Assi",
        "hosted_by": "UF Department of Physics",
        "description": "Weekly high energy physics seminar featuring visiting researchers presenting current work in particle physics and cosmology.",
        "summary": "Weekly high energy physics seminar series.",
        "deadline": "March 24, 2026",
        "hourly_commitment": "12:30 PM - 1:30 PM",
        "location_detail": "Room 2165, New Physics Building (NPB)",
        "tags": ["High Energy Physics", "Seminar", "Particle Physics", "Cosmology"],
        "contact": "UF Department of Physics",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "event",
        "title": "Physics Colloquium - Vladan Vuletic",
        "hosted_by": "UF Department of Physics",
        "description": "Department-wide colloquium featuring invited speakers discussing advances in modern physics research.",
        "summary": "Physics colloquium with invited speakers.",
        "deadline": "March 26, 2026",
        "hourly_commitment": "3:00 PM - 4:00 PM",
        "location_detail": "NPB 1002, New Physics Building",
        "tags": ["Physics", "Colloquium", "Research", "Invited Speaker"],
        "contact": "UF Department of Physics",
        "goal_tags": ["research", "career"],
    },
    {
        "type": "event",
        "title": "Condensed Matter / Biophysics Seminar - Suk Bum Chung",
        "hosted_by": "UF Department of Physics",
        "description": "Research seminar covering theoretical and experimental developments in condensed matter and biophysics.",
        "summary": "Condensed matter and biophysics seminar.",
        "deadline": "March 23, 2026",
        "hourly_commitment": "4:00 PM - 5:00 PM",
        "location_detail": "New Physics Building",
        "tags": ["Condensed Matter", "Biophysics", "Seminar", "Research"],
        "contact": "UF Department of Physics",
        "goal_tags": ["research", "career"],
    },
]
