def _opp(
    *,
    title: str,
    description: str,
    summary: str,
    department: str,
    professor: str,
    tags: list[str],
    contact: str,
    deadline: str,
    hourly_commitment: str,
    pay: str,
    terms_available: str,
    student_level: str,
    prerequisites: str,
    credit: str,
    stipend: str,
    application_requirements: str,
    url: str = "",
    phd_student_mentors: str = "",
    professor_id: str = "",
) -> dict:
    data = {
        "type": "research",
        "title": title,
        "description": description,
        "summary": summary,
        "department": department,
        "professor": professor,
        "phd_student_mentors": phd_student_mentors,
        "terms_available": terms_available,
        "student_level": student_level,
        "prerequisites": prerequisites,
        "credit": credit,
        "stipend": stipend,
        "application_requirements": application_requirements,
        "tags": tags,
        "contact": contact,
        "deadline": deadline,
        "hourly_commitment": hourly_commitment,
        "pay": pay,
        "goal_tags": ["research", "career"],
    }
    if professor_id:
        data["professor_id"] = professor_id
    if url:
        data["url"] = url
    return data


NEW_PHYSICS_RESEARCH_OPPORTUNITIES = [
    _opp(
        title="Institute for High Energy Physics and Astrophysics (IHEPA)",
        description="IHEPA facilitates UF collaborations in large-scale interdisciplinary particle physics and astrophysics projects. Researchers design and construct apparatus, develop major software components, perform data analysis and simulation, and provide large-scale computing support for data reduction and simulation.",
        summary="Particle physics and astrophysics collaboration with experimental, software, and computing work.",
        department="Department of Physics",
        professor="Tanner, David",
        professor_id="npb-david-tanner",
        phd_student_mentors="Board of Directors: David Tanner, Andrey Korytov, Paul Fulda, Sergey Klimenko, Jacobo Konigsberg",
        terms_available="",
        student_level="",
        prerequisites="",
        credit="",
        stipend="",
        application_requirements="Contact Dr. David Tanner at tanner@phys.ufl.edu.",
        tags=["Astrophysics", "Particle Physics", "Simulation", "Computing"],
        contact="tanner@phys.ufl.edu",
        deadline="",
        hourly_commitment="",
        pay="",
    ),
    _opp(
        title="Institute for Fundamental Theory (IFT)",
        description="IFT provides theoretical physicists and mathematicians with an interdisciplinary environment that encourages interaction across high-energy theory, condensed matter theory, astrophysics theory, biophysics theory, and mathematics.",
        summary="Interdisciplinary theory institute spanning physics and mathematics.",
        department="Department of Physics",
        professor="Dror, Jeff",
        professor_id="npb-jeff-dror",
        phd_student_mentors="Associate Director: Sergei Shabanov; Advisory Board: Jeff Andrews, Gabriel Birzu, Dmitrii Maslov",
        terms_available="",
        student_level="",
        prerequisites="",
        credit="",
        stipend="",
        application_requirements="",
        tags=["Astrophysics Theory", "High-Energy Theory", "Biophysics Theory", "Mathematics"],
        contact="",
        deadline="",
        hourly_commitment="",
        pay="",
    ),
    _opp(
        title="Biological Physics Research",
        description="Biological physics at UF explores interdisciplinary questions across physics, biology, chemistry, bioinformatics, physical biology, and systems biology. Research is conducted in laboratories across multiple departments with Physics-affiliated faculty and affiliate faculty.",
        summary="Interdisciplinary biological physics research across physics, biology, and chemistry.",
        department="Department of Physics",
        professor="Hagen, Stephen",
        professor_id="npb-stephen-hagen",
        phd_student_mentors="Department Faculty: Stephen Hagen, Mark Meisel, BingKan Xue, Gabriel Birzu, Thomas Angelini, Emrah Simsek. Affiliate Faculty: Thomas Mareci, Adrian Roitberg.",
        terms_available="",
        student_level="",
        prerequisites="",
        credit="",
        stipend="",
        application_requirements="",
        tags=["Biological Physics", "Bioinformatics", "Physical Biology", "Systems Biology"],
        contact="",
        deadline="",
        hourly_commitment="",
        pay="",
    ),
]
