NEW_PHYSICS_DIRECTORY = [
    {
        "id": "npb-david-tanner",
        "name": "Tanner, David",
        "title": "Distinguished Professor",
        "affiliations": "Institute for High Energy Physics and Astrophysics, Board of Directors",
        "phone": "352-392-4718",
        "location": "2372 NPB",
        "email": "uftanner@ufl.edu",
        "linkedin_url": "",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/10/david-tanner-800x788.jpg",
    },
    {
        "id": "npb-andrey-korytov",
        "name": "Korytov, Andrey",
        "title": "Professor",
        "affiliations": "Institute for High Energy Physics and Astrophysics, Board of Directors",
        "phone": "352.392.3482",
        "location": "2027 NPB",
        "email": "korytov@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/andrey-korytov-73582157/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/11/andrey-korytov-800x949.jpg",
    },
    {
        "id": "npb-paul-fulda",
        "name": "Fulda, Paul",
        "title": "Associate Professor",
        "affiliations": "Institute for High Energy Physics and Astrophysics, Board of Directors",
        "phone": "352-392-1444",
        "location": "2364 NPB",
        "email": "paulfulda@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/paul-fulda-978956a6/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/11/paul-fulda-800x960.jpg",
    },
    {
        "id": "npb-sergey-klimenko",
        "name": "Klimenko, Sergey",
        "title": "Professor",
        "affiliations": "Institute for High Energy Physics and Astrophysics, Board of Directors",
        "phone": "352-392-9225",
        "location": "2019 NPB",
        "email": "klimenko@phys.ufl.edu",
        "linkedin_url": "",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/11/seregy-klimenko-800x995.jpg",
    },
    {
        "id": "npb-jacobo-konigsberg",
        "name": "Konigsberg, Jacobo",
        "title": "Research Professor",
        "affiliations": "Institute for High Energy Physics and Astrophysics, Board of Directors",
        "phone": "352-392-4013",
        "location": "2025 NPB",
        "email": "konigsb@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/jacobo-konigsberg-28b946a9/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2026/02/Jacobo-Konigsberg.jpg",
    },
    {
        "id": "npb-jeff-dror",
        "name": "Dror, Jeff",
        "title": "Assistant Professor",
        "affiliations": "Institute for Fundamental Theory",
        "phone": "",
        "location": "2079 NPB",
        "email": "jeffdror@ufl.edu",
        "linkedin_url": "",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/11/jeff-dror-3-800x942.jpg",
    },
    {
        "id": "npb-sergei-shabanov",
        "name": "Shabanov, Sergei",
        "title": "Professor of Mathematics, Affiliate Professor of Physics",
        "affiliations": "Institute for Fundamental Theory",
        "phone": "352-392-8714",
        "location": "LIT 464 (Mathematics), NPB 2180 (Physics)",
        "email": "shabanov@ufl.edu",
        "linkedin_url": "",
        "image_url": "https://people.clas.ufl.edu/shabanov/files/Shabanov58.jpg",
    },
    {
        "id": "npb-jeff-andrews",
        "name": "Andrews, Jeff",
        "title": "Assistant Professor",
        "affiliations": "Institute for Fundamental Theory, Advisory Board",
        "phone": "352-846-3132",
        "location": "2164 NPB",
        "email": "jeffrey.andrews@ufl.edu",
        "linkedin_url": "",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/10/jeff-andrews-1-768x584.jpg",
    },
    {
        "id": "npb-gabriel-birzu",
        "name": "Birzu, Gabriel",
        "title": "Assistant Professor",
        "affiliations": "Institute for Fundamental Theory, Advisory Board, Biological Physics, Department Faculty",
        "phone": "352-392-6976",
        "location": "2326 NPB",
        "email": "gbirzu@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/gabriel-birzu/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2024/08/Gabriel-Birzu-800x764.jpg",
    },
    {
        "id": "npb-dmitrii-maslov",
        "name": "Maslov, Dmitrii",
        "title": "Professor",
        "affiliations": "Institute for Fundamental Theory, Advisory Board",
        "phone": "352-392-0513",
        "location": "2114 NPB",
        "email": "maslov@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/dmitrii-maslov-30a36290/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/12/dmitrii-maslov-800x961.jpg",
    },
    {
        "id": "npb-stephen-hagen",
        "name": "Hagen, Stephen",
        "title": "Professor & Chair",
        "affiliations": "Biological Physics, Department Faculty",
        "phone": "352-392-4716",
        "location": "2362 NPB",
        "email": "sjhagen@ufl.edu",
        "linkedin_url": "",
        "image_url": "https://people.clas.ufl.edu/sjhagen/files/20191130Housden-1.png",
    },
    {
        "id": "npb-mark-meisel",
        "name": "Meisel, Mark",
        "title": "Professor",
        "affiliations": "Biological Physics, Department Faculty",
        "phone": "352-392-8867",
        "location": "2358 NPB",
        "email": "meisel@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/mark-meisel-32a517250/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2019/08/meisel-sm-800x988.jpg",
    },
    {
        "id": "npb-bingkan-xue",
        "name": "Xue, BingKan",
        "title": "Associate Professor",
        "affiliations": "Biological Physics, Department Faculty",
        "phone": "352-392-6973",
        "location": "2328 NPB",
        "email": "b.xue@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/bingkan-xue-82a91a58/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2023/12/bingkan-xue-800x994.jpg",
    },
    {
        "id": "npb-thomas-angelini",
        "name": "Angelini, Thomas",
        "title": "Professor",
        "affiliations": "Biological Physics, Department Faculty",
        "phone": "352-392-6438",
        "location": "Wertheim 495",
        "email": "t.e.angelini@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/thomas-angelini-a39b0925/",
        "image_url": "https://www.eng.ufl.edu/wp-content/uploads/connections-images/tommy-angelini/angelini-headshot-b982f0d547e2532c7f9776bb23efe179.jpg",
    },
    {
        "id": "npb-emrah-simsek",
        "name": "Simsek, Emrah",
        "title": "Assistant Professor",
        "affiliations": "Biological Physics, Department Faculty",
        "phone": "352-392-3233",
        "location": "2368 NPB",
        "email": "esimsek@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/emrah-simsek-phd/",
        "image_url": "https://www.phys.ufl.edu/wp/wp-content/uploads/2025/09/Emrah-Simsek-768x1024.jpg",
    },
    {
        "id": "npb-thomas-mareci",
        "name": "Mareci, Thomas",
        "title": "Professor Emeritus",
        "affiliations": "Biological Physics, Affiliate Faculty",
        "phone": "352-273-5348",
        "location": "",
        "email": "thmareci@ufl.edu",
        "linkedin_url": "https://www.linkedin.com/in/thomas-mareci-aab3222b/",
        "image_url": "https://directory.ufhealth.org/mareci-thomas/files/profile-photo",
    }
]
